//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.09 at 04:34:34 PM CEST 
//


package at.ac.tuwien.dsg.rSybl.cloudInteractionUnit.celar.dbalancer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Application_QNAME = new QName("", "application");
    private final static QName _AuthenticationResponse_QNAME = new QName("", "authenticationResponse");
    private final static QName _BalancerInfo_QNAME = new QName("", "balancerInfo");
    private final static QName _Flavor_QNAME = new QName("", "flavor");
    private final static QName _Image_QNAME = new QName("", "image");
    private final static QName _AuthenticationRequest_QNAME = new QName("", "authenticationRequest");
    private final static QName _Deployment_QNAME = new QName("", "deployment");
    private final static QName _ServerInfo_QNAME = new QName("", "serverInfo");
    private final static QName _BalancingStatus_QNAME = new QName("", "balancingStatus");
    private final static QName _ElasticityAction_QNAME = new QName("", "elasticityAction");
    private final static QName _StartBalancer_QNAME = new QName("", "startBalancer");
    private final static QName _Probe_QNAME = new QName("", "probe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationInfo }
     * 
     */
    public ApplicationInfo createApplicationInfo() {
        return new ApplicationInfo();
    }

    /**
     * Create an instance of {@link BalancerInfo }
     * 
     */
    public BalancerInfo createBalancerInfo() {
        return new BalancerInfo();
    }

    /**
     * Create an instance of {@link AuthenticationResponse }
     * 
     */
    public AuthenticationResponse createAuthenticationResponse() {
        return new AuthenticationResponse();
    }

    /**
     * Create an instance of {@link Flavor }
     * 
     */
    public Flavor createFlavor() {
        return new Flavor();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link DeploymentInfo }
     * 
     */
    public DeploymentInfo createDeploymentInfo() {
        return new DeploymentInfo();
    }

    /**
     * Create an instance of {@link AuthenticationRequest }
     * 
     */
    public AuthenticationRequest createAuthenticationRequest() {
        return new AuthenticationRequest();
    }

    /**
     * Create an instance of {@link ServerInfo }
     * 
     */
    public ServerInfo createServerInfo() {
        return new ServerInfo();
    }

    /**
     * Create an instance of {@link StartBalancer }
     * 
     */
    public StartBalancer createStartBalancer() {
        return new StartBalancer();
    }

    /**
     * Create an instance of {@link ElasticityAction }
     * 
     */
    public ElasticityAction createElasticityAction() {
        return new ElasticityAction();
    }

    /**
     * Create an instance of {@link BalancingStatus }
     * 
     */
    public BalancingStatus createBalancingStatus() {
        return new BalancingStatus();
    }

    /**
     * Create an instance of {@link Probe }
     * 
     */
    public Probe createProbe() {
        return new Probe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "application")
    public JAXBElement<ApplicationInfo> createApplication(ApplicationInfo value) {
        return new JAXBElement<ApplicationInfo>(_Application_QNAME, ApplicationInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "authenticationResponse")
    public JAXBElement<AuthenticationResponse> createAuthenticationResponse(AuthenticationResponse value) {
        return new JAXBElement<AuthenticationResponse>(_AuthenticationResponse_QNAME, AuthenticationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BalancerInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "balancerInfo")
    public JAXBElement<BalancerInfo> createBalancerInfo(BalancerInfo value) {
        return new JAXBElement<BalancerInfo>(_BalancerInfo_QNAME, BalancerInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Flavor }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "flavor")
    public JAXBElement<Flavor> createFlavor(Flavor value) {
        return new JAXBElement<Flavor>(_Flavor_QNAME, Flavor.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Image }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "image")
    public JAXBElement<Image> createImage(Image value) {
        return new JAXBElement<Image>(_Image_QNAME, Image.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthenticationRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "authenticationRequest")
    public JAXBElement<AuthenticationRequest> createAuthenticationRequest(AuthenticationRequest value) {
        return new JAXBElement<AuthenticationRequest>(_AuthenticationRequest_QNAME, AuthenticationRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeploymentInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deployment")
    public JAXBElement<DeploymentInfo> createDeployment(DeploymentInfo value) {
        return new JAXBElement<DeploymentInfo>(_Deployment_QNAME, DeploymentInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serverInfo")
    public JAXBElement<ServerInfo> createServerInfo(ServerInfo value) {
        return new JAXBElement<ServerInfo>(_ServerInfo_QNAME, ServerInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BalancingStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "balancingStatus")
    public JAXBElement<BalancingStatus> createBalancingStatus(BalancingStatus value) {
        return new JAXBElement<BalancingStatus>(_BalancingStatus_QNAME, BalancingStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElasticityAction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "elasticityAction")
    public JAXBElement<ElasticityAction> createElasticityAction(ElasticityAction value) {
        return new JAXBElement<ElasticityAction>(_ElasticityAction_QNAME, ElasticityAction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartBalancer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "startBalancer")
    public JAXBElement<StartBalancer> createStartBalancer(StartBalancer value) {
        return new JAXBElement<StartBalancer>(_StartBalancer_QNAME, StartBalancer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Probe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "probe")
    public JAXBElement<Probe> createProbe(Probe value) {
        return new JAXBElement<Probe>(_Probe_QNAME, Probe.class, null, value);
    }

}
