//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.09 at 04:34:34 PM CEST 
//


package at.ac.tuwien.dsg.rSybl.cloudInteractionUnit.celar.dbalancer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for startBalancer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="startBalancer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{}balancerType" minOccurs="0"/>
 *         &lt;element name="load" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="threshold" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "startBalancer", propOrder = {
    "type",
    "load",
    "threshold"
})
public class StartBalancer {

    protected BalancerType type;
    protected double load;
    protected double threshold;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link BalancerType }
     *     
     */
    public BalancerType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalancerType }
     *     
     */
    public void setType(BalancerType value) {
        this.type = value;
    }

    /**
     * Gets the value of the load property.
     * 
     */
    public double getLoad() {
        return load;
    }

    /**
     * Sets the value of the load property.
     * 
     */
    public void setLoad(double value) {
        this.load = value;
    }

    /**
     * Gets the value of the threshold property.
     * 
     */
    public double getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     */
    public void setThreshold(double value) {
        this.threshold = value;
    }

}
